# ZAP Configuration File

env:
  contexts:
    - name: "Angular XSS"
      urls:
        - "http://localhost:4200"
      includePaths:
        - "http://localhost:4200.*"
      excludePaths: []
      authentication:
        method: "form"
        loginPageUrl: "http://localhost:4200/home/signin"
        loginRequestUrl: "http://localhost:8000/signin"
        loginRequestBody: "email={%username%}&password={%password%}"
      users:
        - name: "admin"
          username: "admin@example.com"
          password: "admin123"
      indicators:
        - type: "response.header"
          name: "Authorization"
          present: "false"

  parameters:
    failOnWarning: false
    failOnError: true
    progressToStdout: true
    maxAlertsPerRule: 10

addOns:
  enableBruteForce: false
  enableAjaxSpider: true

pscan:
  maxAlertsPerRule: 10
  maxBodySizeInBytesToScan: 2000000

ascan:
  attackStrength: "HIGH"
  alertThreshold: "MEDIUM"
  maxRuleDurationInMins: 5
  maxScanDurationInMins: 60
  delay: 0
  handleAntiCSRFTokens: true
  injectPluginIdInHeader: true
  maxBodySizeInBytesToScan: 2000000
  defaultPolicy: "Default Policy"

ajax:
  browserId: "htmlunit"
  clickDefaultElements: "a,button,input"
  eventWait: 1000
  maxCrawlDepth: 10
  maxCrawlStates: 0
  maxDuration: 0
  numberOfBrowsers: 1

# XSS-specific payloads for this vulnerable application
xss:
  payloads:
    - "javascript:alert('XSS')"
    - "javascript:alert(document.cookie)"
    - "javascript:alert(window.localStorage.getItem('token'))"
